# Sidebar navigation
- label: 'OVERVIEW'
  items:
    - label: 'Introduction'
      link: '/'
    - label: 'SSH-Keys'
      link: '/sshkeys'
- label: 'QUICKSTART GUIDES'
  items:
    - label: 'Installing Exorun'
      link: '/getting-started/installing-exorun'
    - label: 'Run a Node App'
      link: '/getting-started/nodejs'
- label: 'Exorun cli'
  items:
      - label: 'Register'
        link: '/register'
      - label: 'Login'
        link: '/login'
      - label: 'Logout'
        link: '/logout'
      - label: 'List'
        link: '/instance-list'
      - label: 'Create instance'
        link: '/create-instance'
      - label: 'Delete instance'
        link: '/delete-instance'
      - label: 'Templates'
        link: '/templates'
      - label: 'Template'
        link: '/template'
      - label: 'Regions'
        link: '/regions'